swagger: '2.0'
info:
  title: DagAir Policies API v1
  version: v1
paths:
  '/policies-api/expected-room-conditions/{expectedRoomConditionsId}':
    get:
      tags:
        - ExpectedRoomConditions
      summary: Returns information about a set of expected room conditions with a given expectedRoomConditionsId
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: expectedRoomConditionsId
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ExpectedRoomConditionsDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
  /policies-api/expected-room-conditions:
    post:
      tags:
        - ExpectedRoomConditions
      summary: Creates new set of expected conditions with parameters specified in addNewExpectedRoomConditionsCommand
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          description: ''
          schema:
            $ref: '#/definitions/AddNewExpectedRoomConditionsCommand'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/ExpectedRoomConditionsDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
  '/policies-api/policies/{roomId}':
    get:
      tags:
        - Policies
      summary: Returns information about a policy currently in force in a room with a given roomId
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: roomId
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/RoomPolicyDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
  /policies-api/policies:
    post:
      tags:
        - Policies
      summary: Create a new policy with parameters specified in addNewRoomPolicyCommand
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          description: ''
          schema:
            $ref: '#/definitions/AddNewRoomPolicyCommand'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/RoomPolicyDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
  /policies-api/policies/past-policies:
    post:
      tags:
        - Policies
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/GetPastPoliciesCommand'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/PastMeasurementsDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
definitions:
  AddNewExpectedRoomConditionsCommand:
    type: object
    properties:
      expectedRoomConditionsDto:
        $ref: '#/definitions/ExpectedRoomConditionsDto'
  AddNewRoomPolicyCommand:
    type: object
    properties:
      roomPolicyDto:
        $ref: '#/definitions/RoomPolicyDto'
      expectedRoomConditionsDto:
        $ref: '#/definitions/ExpectedRoomConditionsDto'
      roomPolicyCategoryDto:
        $ref: '#/definitions/RoomPolicyCategoryDto'
  ExpectedRoomConditionsDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      temperature:
        format: double
        type: number
      illuminance:
        format: int32
        type: integer
      humidity:
        format: double
        type: number
      temperatureMargin:
        format: double
        type: number
      illuminanceMargin:
        format: double
        type: number
      humidityMargin:
        format: double
        type: number
      roomPolicyId:
        format: int64
        type: integer
  ExpectedRoomConditionsDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/ExpectedRoomConditionsDto'
  GetPastPoliciesCommand:
    type: object
    properties:
      roomId:
        format: int64
        type: integer
      historicMeasurements:
        type: array
        items:
          $ref: '#/definitions/HistoricMeasurement'
  HistoricMeasurement:
    type: object
    properties:
      temperature:
        format: double
        type: number
      illuminance:
        format: int32
        type: integer
      humidity:
        format: double
        type: number
      date:
        format: date-time
        type: string
  HistoricMeasurementRoomPolicyDtoTuple:
    type: object
    properties:
      item1:
        $ref: '#/definitions/HistoricMeasurement'
      item2:
        $ref: '#/definitions/RoomPolicyDto'
  JsonApiError:
    type: object
    properties:
      message:
        type: string
        readOnly: true
      messageDetails:
        type: string
  PastMeasurementsDto:
    type: object
    properties:
      measurements:
        type: array
        items:
          $ref: '#/definitions/HistoricMeasurementRoomPolicyDtoTuple'
  PastMeasurementsDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/PastMeasurementsDto'
  RoomPolicyCategoryDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      categoryNumber:
        format: int32
        type: integer
  RoomPolicyDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      startDate:
        format: date-time
        type: string
      endDate:
        format: date-time
        type: string
      startHour:
        format: int32
        type: integer
      endHour:
        format: int32
        type: integer
      repeatOn:
        type: string
      expectedConditionsId:
        format: int64
        type: integer
      categoryId:
        format: int64
        type: integer
      roomId:
        format: int64
        type: integer
      expectedConditions:
        $ref: '#/definitions/ExpectedRoomConditionsDto'
      category:
        $ref: '#/definitions/RoomPolicyCategoryDto'
  RoomPolicyDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/RoomPolicyDto'