version: "3.9"

services:
  sensors_api:
    build:
      target: final
      context: ./src
      dockerfile: ./DagAir_Sensors/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DagAir.Sensors=server=host.docker.internal;database=DagAir.Sensors;user=root;password=
      - ConnectionKeys__DagAir.Sensors=${SENSORS_CONNECTIONKEYS}
    ports:
      - "9002:80"
    networks:
      - dagair_network
    restart: always
  
  policies_api:
    build:
      target: final
      context: ./src
      dockerfile: ./DagAir_Policies/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DagAir.Policies=server=host.docker.internal;database=DagAir.Policies;user=root;password=
      - ConnectionKeys__DagAir.Policies=${POLICIES_CONNECTIONKEYS}
    ports:
      - "12000:80"
    networks:
      - dagair_network
    restart: always

  facilities_api:
    build:
      target: final
      context: ./src
      dockerfile: ./DagAir_Facilities/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DagAir.Facilities=server=host.docker.internal;database=DagAir.Facilities;user=root;password=
      - ConnectionKeys__DagAir.Facilities=${FACILITIES_CONNECTIONKEYS}
    ports:
      - "15000:80"
    networks:
      - dagair_network
    restart: always

  addresses_api:
    build:
      target: final
      context: ./src
      dockerfile: ./DagAir_Addresses/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DagAir.Addresses=server=host.docker.internal;database=DagAir.Addresses;user=root;password=
      - ConnectionKeys__DagAir.Addresses=${ADDRESSES_CONNECTIONKEYS}
    ports:
      - "10000:80"
    networks:
      - dagair_network
    restart: always

networks:
  dagair_network: