docker tag dagair_sensors_api sensors-api:1.6
docker tag dagair_policies_api policies-api:1.6
docker tag dagair_facilities_api facilities-api:1.6
docker tag dagair_addresses_api addresses-api:1.6
docker tag dagair_sensor_state_history_api sensor-state-history-api:1.6
docker tag dagair_sensor_state_api sensor-state-api:1.6
docker tag dagair_ingestion_node ingestion-node:1.6
docker tag dagair_policy_node policy-node:1.6
docker tag dagair_client_node client-node:1.6
docker tag dagair_admin_node admin-node:1.6
docker tag dagair_web_client_app web-client-app:1.6
docker tag dagair_web_admin_app web-admin-app:1.6
docker tag dagair_subscriber subscriber:1.6