minikube image load sensors-api:1.6
minikube image load policies-api:1.6
minikube image load addresses-api:1.6
minikube image load facilities-api:1.6
minikube image load sensor-state-history-api:1.6
minikube image load sensor-state-api:1.6
minikube image load ingestion-node:1.6
minikube image load policy-node:1.6
minikube image load web-admin-app:1.6
minikube image load admin-node:1.6
minikube image load redis:1.6
minikube image load realtime/notification-producer:1.6
minikube image load subscriber:1.6