minikube image rm sensors-api:1.6
minikube image rm policies-api:1.6
minikube image rm addresses-api:1.6
minikube image rm facilities-api:1.6
minikube image rm sensor-state-history-api:1.6
minikube image rm sensor-state-api:1.6
minikube image rm ingestion-node:1.6
minikube image rm policy-node:1.6
minikube image rm web-admin-app:1.6
minikube image rm admin-node:1.6
minikube image rm redis:1.6
minikube image rm realtime/notification-producer:1.6