// <auto-generated />
using System;
using DagAir.Policies.Data.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DagAir.Policies.Data.Migrations.Migrations
{
    [DbContext(typeof(DagAirPoliciesAppContext))]
    [Migration("20211030180151_AddCategoryNumberColumn")]
    partial class AddCategoryNumberColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DagAir.Policies")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.ExpectedRoomConditions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("(CURRENT_DATE)");

                    b.Property<float>("Humidity")
                        .HasColumnType("float")
                        .HasColumnName("humidity");

                    b.Property<float>("HumidityMargin")
                        .HasColumnType("float")
                        .HasColumnName("humidity_margin");

                    b.Property<float>("Illuminance")
                        .HasColumnType("float")
                        .HasColumnName("illuminance");

                    b.Property<float>("IlluminanceMargin")
                        .HasColumnType("float")
                        .HasColumnName("illuminance_margin");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime")
                        .HasColumnName("modified");

                    b.Property<long?>("RoomPolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_policy_id");

                    b.Property<float>("Temperature")
                        .HasColumnType("float")
                        .HasColumnName("temperature");

                    b.Property<float>("TemperatureMargin")
                        .HasColumnType("float")
                        .HasColumnName("temperature_margin");

                    b.HasKey("Id")
                        .HasName("pk_expected_room_conditions");

                    b.ToTable("expected_room_conditions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 0.4f,
                            HumidityMargin = 0.1f,
                            Illuminance = 100f,
                            IlluminanceMargin = 20f,
                            Temperature = 20f,
                            TemperatureMargin = 2f
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 0.5f,
                            HumidityMargin = 0.1f,
                            Illuminance = 130f,
                            IlluminanceMargin = 30f,
                            Temperature = 22f,
                            TemperatureMargin = 3f
                        });
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("(CURRENT_DATE)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<long>("ExpectedConditionsId")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_conditions_id");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime")
                        .HasColumnName("modified");

                    b.Property<string>("RepeatOn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("repeat_on");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_room_policies");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_room_policies_category_id");

                    b.HasIndex("ExpectedConditionsId")
                        .IsUnique()
                        .HasDatabaseName("ix_room_policies_expected_conditions_id");

                    b.ToTable("room_policies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2021, 10, 30, 22, 1, 51, 0, DateTimeKind.Unspecified),
                            ExpectedConditionsId = 1L,
                            RepeatOn = "Monday, Thursday",
                            RoomId = 1L,
                            StartDate = new DateTime(2021, 10, 30, 20, 1, 51, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2021, 10, 30, 21, 1, 51, 0, DateTimeKind.Unspecified),
                            ExpectedConditionsId = 2L,
                            RepeatOn = "Wednesday",
                            RoomId = 1L,
                            StartDate = new DateTime(2021, 10, 30, 17, 1, 51, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicyCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("CategoryNumber")
                        .HasColumnType("int")
                        .HasColumnName("category_number");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("(CURRENT_DATE)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_room_policy_categories");

                    b.ToTable("room_policy_categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryNumber = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryNumber = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Organizational"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryNumber = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Departmental"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryNumber = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicy", b =>
                {
                    b.HasOne("DagAir.Policies.Data.AppEntities.RoomPolicyCategory", "Category")
                        .WithMany("RoomPolicies")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_room_policies_room_policy_categories_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DagAir.Policies.Data.AppEntities.ExpectedRoomConditions", "ExpectedConditions")
                        .WithOne("RoomPolicy")
                        .HasForeignKey("DagAir.Policies.Data.AppEntities.RoomPolicy", "ExpectedConditionsId")
                        .HasConstraintName("fk_room_policies_expected_room_conditions_expected_conditions_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ExpectedConditions");
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.ExpectedRoomConditions", b =>
                {
                    b.Navigation("RoomPolicy");
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicyCategory", b =>
                {
                    b.Navigation("RoomPolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
