// <auto-generated />
using System;
using DagAir.Policies.Data.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DagAir.Policies.Data.Migrations.Migrations
{
    [DbContext(typeof(DagAirPoliciesAppContext))]
    [Migration("20220115103804_ModifyRoomPolicyEntity")]
    partial class ModifyRoomPolicyEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DagAir.Policies")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.ExpectedRoomConditions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("humidity");

                    b.Property<decimal>("HumidityMargin")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("humidity_margin");

                    b.Property<int>("Illuminance")
                        .HasColumnType("int")
                        .HasColumnName("illuminance");

                    b.Property<decimal>("IlluminanceMargin")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("illuminance_margin");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime")
                        .HasColumnName("modified");

                    b.Property<long?>("RoomPolicyId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_policy_id");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("temperature");

                    b.Property<decimal>("TemperatureMargin")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("temperature_margin");

                    b.HasKey("Id")
                        .HasName("pk_expected_room_conditions");

                    b.ToTable("expected_room_conditions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 0.4m,
                            HumidityMargin = 0.1m,
                            Illuminance = 100,
                            IlluminanceMargin = 20m,
                            Temperature = 20m,
                            TemperatureMargin = 2m
                        },
                        new
                        {
                            Id = 2L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Humidity = 0.5m,
                            HumidityMargin = 0.1m,
                            Illuminance = 130,
                            IlluminanceMargin = 30m,
                            Temperature = 22m,
                            TemperatureMargin = 3m
                        });
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<int>("EndHour")
                        .HasColumnType("int")
                        .HasColumnName("end_hour");

                    b.Property<long>("ExpectedConditionsId")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_conditions_id");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime")
                        .HasColumnName("modified");

                    b.Property<string>("RepeatOn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("repeat_on");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<int>("StartHour")
                        .HasColumnType("int")
                        .HasColumnName("start_hour");

                    b.HasKey("Id")
                        .HasName("pk_room_policies");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_room_policies_category_id");

                    b.HasIndex("ExpectedConditionsId")
                        .HasDatabaseName("ix_room_policies_expected_conditions_id");

                    b.ToTable("room_policies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "dd8db40b-c091-4d12-a185-b2f71f369917",
                            EndDate = new DateTime(2023, 1, 15, 13, 38, 3, 0, DateTimeKind.Unspecified),
                            EndHour = 12,
                            ExpectedConditionsId = 1L,
                            RepeatOn = "Monday, Thursday",
                            RoomId = 1L,
                            StartDate = new DateTime(2022, 1, 15, 11, 38, 3, 0, DateTimeKind.Unspecified),
                            StartHour = 10
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "dd8db40b-c091-4d12-a185-b2f71f369917",
                            EndDate = new DateTime(2023, 1, 15, 12, 38, 3, 0, DateTimeKind.Unspecified),
                            EndHour = 14,
                            ExpectedConditionsId = 2L,
                            RepeatOn = "Wednesday",
                            RoomId = 1L,
                            StartDate = new DateTime(2022, 1, 15, 8, 38, 3, 0, DateTimeKind.Unspecified),
                            StartHour = 12
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2L,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "dd8db40b-c091-4d12-a185-b2f71f369917",
                            EndDate = new DateTime(2022, 10, 5, 23, 59, 59, 0, DateTimeKind.Unspecified),
                            EndHour = 6,
                            ExpectedConditionsId = 2L,
                            RepeatOn = "",
                            RoomId = 1L,
                            StartDate = new DateTime(2021, 11, 5, 1, 1, 1, 0, DateTimeKind.Unspecified),
                            StartHour = 22
                        });
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicyCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("CategoryNumber")
                        .HasColumnType("int")
                        .HasColumnName("category_number");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime")
                        .HasColumnName("modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_room_policy_categories");

                    b.ToTable("room_policy_categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryNumber = 0,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryNumber = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Organizational"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryNumber = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Departmental"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryNumber = 3,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicy", b =>
                {
                    b.HasOne("DagAir.Policies.Data.AppEntities.RoomPolicyCategory", "Category")
                        .WithMany("RoomPolicies")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_room_policies_room_policy_categories_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DagAir.Policies.Data.AppEntities.ExpectedRoomConditions", "ExpectedConditions")
                        .WithMany("RoomPolicies")
                        .HasForeignKey("ExpectedConditionsId")
                        .HasConstraintName("fk_room_policies_expected_room_conditions_expected_conditions_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ExpectedConditions");
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.ExpectedRoomConditions", b =>
                {
                    b.Navigation("RoomPolicies");
                });

            modelBuilder.Entity("DagAir.Policies.Data.AppEntities.RoomPolicyCategory", b =>
                {
                    b.Navigation("RoomPolicies");
                });
#pragma warning restore 612, 618
        }
    }
}
