swagger: '2.0'
info:
  title: DagAir Admin Node v1
  version: v1
paths:
  /admin-node/addresses:
    post:
      tags:
        - AddressesAdmin
      consumes:
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/AddNewAddressCommand'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/AddressDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
  /admin-node/affiliates:
    get:
      tags:
        - AffiliatesAdmin
      summary: Returns information about all affiliates
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AdminNodeAffiliateDtoListJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
    post:
      tags:
        - AffiliatesAdmin
      consumes:
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/AddNewAffiliateCommand'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/AffiliateDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/JsonApiError'
  '/admin-node/affiliates/{affiliateId}':
    get:
      tags:
        - AffiliatesAdmin
      summary: Returns information about an affiliate with a given affiliateId
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: affiliateId
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AdminNodeAffiliateDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
  /admin-node/organizations:
    get:
      tags:
        - FacilitiesAdmin
      summary: Returns information about all organizations
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AdminNodeOrganizationDtoListJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
    post:
      tags:
        - FacilitiesAdmin
      consumes:
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/AddNewOrganizationCommand'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/OrganizationDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
  '/admin-node/organizations/{organizationId}':
    get:
      tags:
        - FacilitiesAdmin
      summary: Returns information about an organization with a given organizationId
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: organizationId
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/AdminNodeOrganizationDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
  /admin-node/rooms:
    post:
      tags:
        - RoomsAdmin
      consumes:
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/AddNewRoomCommand'
      responses:
        '201':
          description: Success
          schema:
            $ref: '#/definitions/RoomDtoJsonApiDocument'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/JsonApiError'
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/JsonApiError'
definitions:
  AddNewAddressCommand:
    type: object
    properties:
      addressDto:
        $ref: '#/definitions/AddressDto'
      cityDto:
        $ref: '#/definitions/CityDto'
      countryDto:
        $ref: '#/definitions/CountryDto'
      postalCodeDto:
        $ref: '#/definitions/PostalCodeDto'
  AddNewAffiliateCommand:
    type: object
    properties:
      affiliateDto:
        $ref: '#/definitions/AffiliateDto'
  AddNewOrganizationCommand:
    type: object
    properties:
      organizationDto:
        $ref: '#/definitions/OrganizationDto'
  AddNewRoomCommand:
    type: object
    properties:
      roomDto:
        $ref: '#/definitions/RoomDto'
  AddressDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      countryId:
        format: int64
        type: integer
      cityId:
        format: int64
        type: integer
      postalCodeId:
        format: int64
        type: integer
      country:
        $ref: '#/definitions/CountryDto'
      city:
        $ref: '#/definitions/CityDto'
      postalCode:
        $ref: '#/definitions/PostalCodeDto'
  AddressDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/AddressDto'
  AdminNodeAffiliateDto:
    type: object
    properties:
      affiliateDto:
        $ref: '#/definitions/AffiliateDto'
      addressDto:
        $ref: '#/definitions/AddressDto'
  AdminNodeAffiliateDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/AdminNodeAffiliateDto'
  AdminNodeAffiliateDtoListJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/AdminNodeAffiliateDto'
  AdminNodeOrganizationDto:
    type: object
    properties:
      organizationDto:
        $ref: '#/definitions/OrganizationDto'
      addressDto:
        $ref: '#/definitions/AddressDto'
  AdminNodeOrganizationDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/AdminNodeOrganizationDto'
  AdminNodeOrganizationDtoListJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/AdminNodeOrganizationDto'
  AffiliateDto:
    required:
      - name
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      addressId:
        format: int64
        type: integer
      organizationId:
        format: int64
        type: integer
      organization:
        $ref: '#/definitions/OrganizationDto'
      rooms:
        type: array
        items:
          $ref: '#/definitions/RoomDto'
  AffiliateDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/AffiliateDto'
  CityDto:
    required:
      - name
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      addresses:
        type: array
        items:
          $ref: '#/definitions/AddressDto'
  CountryDto:
    required:
      - name
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      addresses:
        type: array
        items:
          $ref: '#/definitions/AddressDto'
  JsonApiError:
    type: object
    properties:
      message:
        type: string
        readOnly: true
      messageDetails:
        type: string
  OrganizationDto:
    required:
      - name
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      addressId:
        format: int64
        type: integer
      affiliates:
        type: array
        items:
          $ref: '#/definitions/AffiliateDto'
  OrganizationDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/OrganizationDto'
  PostalCodeDto:
    required:
      - number
    type: object
    properties:
      id:
        format: int64
        type: integer
      number:
        type: string
      addresses:
        type: array
        items:
          $ref: '#/definitions/AddressDto'
  RoomDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      uniqueRoomId:
        format: uuid
        type: string
      number:
        type: string
      floor:
        format: int32
        type: integer
      affiliateId:
        format: int64
        type: integer
      affiliate:
        $ref: '#/definitions/AffiliateDto'
  RoomDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/RoomDto'