swagger: '2.0'
info:
  title: DagAir Sensors API v1
  version: v1
paths:
  /sensors-api/sensors:
    get:
      tags:
        - Sensors
      summary: Returns information about all sensors
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SensorDtoListJsonApiDocument'
  '/sensors-api/sensors/{sensorId}':
    get:
      tags:
        - Sensors
      summary: Returns information about a sensor with a given sensorId
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: sensorId
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SensorDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
  '/sensors-api/sensors/room-id/{roomId}':
    get:
      tags:
        - Sensors
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: path
          name: roomId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SensorDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
  /sensors-api/sensors/sensor-name:
    post:
      tags:
        - Sensors
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/GetSensorBySensorNameCommand'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SensorDtoJsonApiDocument'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/JsonApiError'
definitions:
  GetSensorBySensorNameCommand:
    type: object
    properties:
      sensorName:
        type: string
  JsonApiError:
    type: object
    properties:
      message:
        type: string
        readOnly: true
      messageDetails:
        type: string
  ProducerDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      dateOfEstablishment:
        format: date-time
        type: string
      addressId:
        format: int64
        type: integer
      sensorModels:
        type: array
        items:
          $ref: '#/definitions/SensorModelDto'
  SensorDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      sensorName:
        type: string
      lastDataSentDate:
        format: date-time
        type: string
      sensorModelId:
        format: int64
        type: integer
      roomId:
        format: int64
        type: integer
      affiliateId:
        format: int64
        type: integer
      sensorModel:
        $ref: '#/definitions/SensorModelDto'
  SensorDtoJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        $ref: '#/definitions/SensorDto'
  SensorDtoListJsonApiDocument:
    required:
      - data
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/SensorDto'
  SensorModelDto:
    type: object
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
      version:
        type: string
      producerId:
        format: int64
        type: integer
      producer:
        $ref: '#/definitions/ProducerDto'
      sensors:
        type: array
        items:
          $ref: '#/definitions/SensorDto'