name: continuous-integration

on:
  workflow_dispatch: # allows to trigger workflow on demand
  push:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.102

      - name: Build @ Test
        shell: bash
        run: ./build.sh --verbosity verbose