name: e2e-tests

on:
  workflow_dispatch: # allows to trigger workflow on demand
  schedule:
    - cron '9 0 * * *' # every day at 9:00 A.M UTC
  push:
    branches:
      - main
      - develop

jobs:
  e2e-tests-runner:
    runs-on: ubuntu-latest